feature/aelf-redesign-part1: Companion wallet design part 1 updates
yongenaelf/ledger-companion-wallet pull request #6
Opened 2023-10-25 06:49 UTC by Faizal-aelf

feature/aelf-redesign-part1: Companion wallet design part 1 updates.

2023-11-14 07:04 UTC, yongenaelf commented on components/common/card/index.tsx
> +import useStyles from "./style";
Don't use "useStyles", use CSS Modules: https://nextjs.org/docs/app/building-your-application/styling/css-modules

By convention, "useFunctionName" should be a React Hook.

2023-11-14 07:15 UTC, Faizal-aelf commented on components/common/card/index.tsx
> +import useStyles from "./style";
Updated

2023-11-14 07:19 UTC, yongenaelf commented on components/common/card/index.tsx
> +import useStyles from "./style";
`import styles from "./style.module.css"`

2023-11-14 07:58 UTC, yongenaelf requested changes

2023-11-14 07:58 UTC, yongenaelf commented on components/common/copyToClipboard/index.tsx
> +    <Flex style={{display: 'inline-flex'}} onClick={() => setSnackbar.success("Copied successfully")}>
Don't use inline style, use CSS Modules

2023-11-14 07:58 UTC, yongenaelf commented on components/common/header/index.tsx
> +import logoMainnetImage from '../../../assets/icon/logo-mainnet.svg';
Use module aliases to avoid traversing up the directory tree: https://nextjs.org/docs/app/building-your-application/configuring/absolute-imports-and-module-aliases

2023-11-14 07:58 UTC, yongenaelf commented on components/common/snackbar/index.tsx
> +        style={{marginLeft: '8px', fontSize: 13}}
Use CSS Modules

2023-11-14 07:58 UTC, yongenaelf commented on components/transactions/components/AllTransactions.tsx
> +        <Tag style={styles.blockTag}>{text}</Tag>
Use CSS Modules

2023-11-14 07:58 UTC, yongenaelf commented on components/transactions/components/AllTransactions.tsx
> +          {showDate ? "Date Time" : "Age"}  <SwapOutlined style={{cursor: 'pointer'}}/>
Use CSS Modules

2023-11-14 07:58 UTC, yongenaelf commented on components/transactions/components/TransferVerification.tsx
> +    tokenContractAddress: any;
In general we should avoid using the "any" type

2023-11-14 07:58 UTC, yongenaelf commented on components/transactions/components/TransferVerification.tsx
> +//{!getFormattedAddress(data.to, chain).endsWith(chain) && <Typography.Text type="secondary" style={styles.modalInfo}>You are about to transfer from {CHAIN_OPTIONS[chain]} to {getChainFromAddress(get
Is this code needed? If not, you can delete it, we can always search the history if we need it back.

2023-11-14 07:58 UTC, yongenaelf commented on components/overview/constants.ts
Move to top level `constants.ts` so that you can do this:

`import {MAINNET_SIDECHAIN_OPTIONS} from "@/constants"`

2023-11-14 07:58 UTC, yongenaelf commented on components/transactions/constants.ts
Move to top level constants.ts so that you can do this:

import {MAINNET_SIDECHAIN_OPTIONS} from "@/constants"

2023-11-14 07:58 UTC, yongenaelf commented on utils/constants.ts
Move to top level constants.ts so that you can do this:

import {YOUR_CONSTANT} from "@/constants"

2023-11-14 07:58 UTC, yongenaelf commented on components/common/card/style.ts
Use CSS Modules

2023-11-14 07:58 UTC, yongenaelf commented on components/common/copyToClipboard/style.ts
Use CSS Modules

2023-11-14 07:58 UTC, yongenaelf commented on components/common/details/style.ts
Use CSS Modules

2023-11-14 07:58 UTC, yongenaelf commented on components/common/footer/style.ts
Use CSS Modules

2023-11-14 07:58 UTC, yongenaelf commented on components/common/formField/style.ts
Use CSS Modules

2023-11-14 07:58 UTC, yongenaelf commented on components/common/header/style.ts
Use CSS Modules

2023-11-14 07:58 UTC, yongenaelf commented on components/common/loader/style.ts
Use CSS Modules

2023-11-14 07:58 UTC, yongenaelf commented on components/common/paperLayout/style.ts
Use CSS Modules

2023-11-14 07:58 UTC, yongenaelf commented on components/overview/style.ts
Use CSS Modules

2023-11-14 07:58 UTC, yongenaelf commented on components/pages/dashboardPage/style.ts
Use CSS Modules

2023-11-14 07:58 UTC, yongenaelf commented on components/pages/errorPage/style.ts
Use CSS Modules

2023-11-14 07:58 UTC, yongenaelf commented on components/pages/homePage/style.ts
Use CSS Modules

2023-11-14 07:58 UTC, yongenaelf commented on components/transactions/style.ts
Use CSS Modules

2023-11-14 07:58 UTC, yongenaelf commented on utils/utils.ts
Split this file into multiple files, named by the function name:

`middleEllipsis.ts`, `endEllipsis.ts`, ...

This will allow quick navigation inside IDE.

2023-11-14 07:58 UTC, yongenaelf commented on utils/validateAddress.ts
> +    const otherChains = chains?.[network]?.[chain];
Can simplify this. This will not work if there are more than 2 chains per network.

2023-11-15 01:36 UTC, Faizal-aelf commented on components/common/card/index.tsx
> +import useStyles from "./style";
Updated

2023-11-15 01:36 UTC, Faizal-aelf commented on components/common/copyToClipboard/index.tsx
> +    <Flex style={{display: 'inline-flex'}} onClick={() => setSnackbar.success("Copied successfully")}>
Updated

2023-11-15 01:36 UTC, Faizal-aelf commented on components/common/snackbar/index.tsx
> +        style={{marginLeft: '8px', fontSize: 13}}
Updated

2023-11-15 01:36 UTC, Faizal-aelf commented on components/transactions/components/AllTransactions.tsx
> +        <Tag style={styles.blockTag}>{text}</Tag>
Updated

2023-11-15 01:45 UTC, Faizal-aelf commented on components/transactions/components/AllTransactions.tsx
> +          {showDate ? "Date Time" : "Age"}  <SwapOutlined style={{cursor: 'pointer'}}/>
Updated

2023-11-15 01:45 UTC, Faizal-aelf commented on components/pages/errorPage/style.ts
Updated

2023-11-15 01:46 UTC, Faizal-aelf commented on components/pages/homePage/style.ts
Updated

2023-11-15 01:46 UTC, Faizal-aelf commented on components/transactions/style.ts
Updated

2023-11-15 01:46 UTC, Faizal-aelf commented on utils/utils.ts
Updated

2023-11-15 01:47 UTC, Faizal-aelf commented on utils/validateAddress.ts
> +    const otherChains = chains?.[network]?.[chain];
Currently we doing for same chain alone.

2023-11-15 01:50 UTC, Faizal-aelf commented on components/transactions/components/TransferVerification.tsx
> +//{!getFormattedAddress(data.to, chain).endsWith(chain) && <Typography.Text type="secondary" style={styles.modalInfo}>You are about to transfer from {CHAIN_OPTIONS[chain]} to {getChainFromAddress(get
Updated

2023-11-15 01:51 UTC, Faizal-aelf commented on components/common/card/style.ts
Updated

2023-11-15 01:51 UTC, Faizal-aelf commented on components/common/copyToClipboard/style.ts
Updated

2023-11-15 01:51 UTC, Faizal-aelf commented on components/common/details/style.ts
Updated

2023-11-15 01:51 UTC, Faizal-aelf commented on components/common/footer/style.ts
Updated

2023-11-15 01:51 UTC, Faizal-aelf commented on components/common/formField/style.ts
Updated

2023-11-15 01:51 UTC, Faizal-aelf commented on components/common/header/style.ts
Updated

2023-11-15 01:51 UTC, Faizal-aelf commented on components/common/loader/style.ts
Updated

2023-11-15 01:51 UTC, Faizal-aelf commented on components/common/paperLayout/style.ts
Updated

2023-11-15 01:51 UTC, Faizal-aelf commented on components/overview/style.ts
Updated

2023-11-15 01:51 UTC, Faizal-aelf commented on components/pages/dashboardPage/style.ts
Updated

2023-11-15 02:25 UTC, Faizal-aelf commented on components/overview/constants.ts
Updated

2023-11-15 02:25 UTC, Faizal-aelf commented on components/common/header/index.tsx
> +import logoMainnetImage from '../../../assets/icon/logo-mainnet.svg';
Updated

2023-11-15 02:25 UTC, Faizal-aelf commented on components/transactions/constants.ts
Updated

2023-11-15 02:25 UTC, Faizal-aelf commented on utils/constants.ts
Updated

2023-11-15 02:25 UTC, Faizal-aelf commented on utils/utils.ts
Updated

2023-11-15 02:28 UTC, Faizal-aelf commented on components/transactions/components/TransferVerification.tsx
> +    tokenContractAddress: any;
Updated

2023-11-15 03:29 UTC, yongenaelf requested changes

2023-11-15 03:29 UTC, yongenaelf commented on components/pages/dashboardPage/index.tsx
> +    <Layout className="layout-container">
Move this global style from App.css into CSS Module

2023-11-15 03:29 UTC, yongenaelf commented on utils/Elf.ts
> +export * from ".";
Remove redundant export

2023-11-15 03:43 UTC, Faizal-aelf commented on components/pages/dashboardPage/index.tsx
> +    <Layout className="layout-container">
Updated

2023-11-15 03:43 UTC, Faizal-aelf commented on utils/Elf.ts
> +export * from ".";
Updated

2023-11-15 05:38 UTC, yongenaelf approved these changes

2023-11-21 08:06 UTC, merged